apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-shark-app-deployment
spec:
  selector:
      matchLabels:
        app: nodejs-shark-app
  replicas: 2
  template:
    metadata:
      labels:
        app: nodejs-shark-app
    spec:
      containers:
        - name: nodejs-shark-app
          image: docker.io/voicestreams/nodejs-shark-app:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
